name: Complex

on: [push]

jobs: 
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: date
  windows:
    runs-on: windows-latest
    steps:
      - run: date
  MacOS:
    runs-on: macos-latest
    steps:
      - run: echo "I DID A MAC THING"
  depends:
    needs: [ubuntu,windows,MacOS] 
    runs-on: macos-latest
    steps:
      - run: date
  
  
